arm:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  #kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  #kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  #position_only_ik: true