#change this
#footprint: [[0.26, 0.18],
#            [0.26, 0.014],
#            [0.31, 0.014],
#            [0.31, -0.014],
#            [0.26, -0.014],
#            [0.26, -0.18],
#            [-0.27, -0.18],
#            [-0.27, 0.18]]
            
# use for youbot+lds_lfcd_sensor
footprint: [[0.26, 0.18],
            [0.26, 0.03],
            [0.37, 0.025],
            [0.37, -0.025],
            [0.26, -0.03],
            [0.26, -0.18],
            [-0.27, -0.18],
            [-0.27, 0.18]]

controller_frequency: 10.0
controller_patience: 15.0
clearing_radius: 0.25
footprint_padding: 0.03

