base_link: base_link

gripper:
  end_effector_name: arm_1_gripper

  # Default grasp params
  joint_list: [gripper_finger_joint_l, gripper_finger_joint_r]

  pregrasp_posture:          [1.0, 1.0]
  pregrasp_time_from_start:  &time_from_start 4.0

  grasp_posture:             [0.0, 0.0]
  grasp_time_from_start:     *time_from_start

  postplace_time_from_start: *time_from_start

  # Desired pose from end effector to grasp [x, y, z] + [R, P, Y]
  grasp_pose_to_eef:          [0.0, 0.0, 0.0]
  grasp_pose_to_eef_rotation_alias: [0.0, 0.0, 0.0]

  end_effector_parent_link: gripper_palm_link
